In [1]:
import numpy as np
import pandas as pd

In [4]:
class Changes:
  def change(k):
    print(k.replace('a','x'))
  def change1(h):
    g=h-int(h)
    print(g)
Changes.change('apple')
Changes.change1(1.4756294)

xpple
0.4756294000000001
xpple
0.4756294000000001


In [34]:
#2. feladat
A=np.array([[5,6,8],[2,3,2]])
B=np.array([[1,3,1],[2,3,3]])
#1.Their dot product
print("1. feladat")
a=A.shape
b=B.shape
if a[1] == b[0]:
  print("Az A és B szorzata: ", np.dot(A,B))
else:
  print("Nem lehetséges")
#2.Their elementwise product
print("2. feladat")
print(A*B)
#3.Their sum
print("3. feladat")
print(A+B)
#4. The sum of the A matrix elements
print("4. feladat")
print(np.sum(A))
#5. The first (index 0) row of the B matrix
print("5. feladat")
print(B[0,0:])
#6. The second (index 1) column of the B matrix
print("6. feladat")
print(B [:, 1])
#7. Create a C matrix from A without A's first column
print("7. feladat")
C=A[:, 1:3]
print(C)

1. feladat
Nem lehetséges
2. feladat
[[ 5 18  8]
 [ 4  9  6]]
3. feladat
[[6 9 9]
 [4 6 5]]
4. feladat
26
5. feladat
[1 3 1]
6. feladat
[3 3]
7. feladat
[[6 8]
 [3 2]]


In [60]:
#3. feladat
def morse(code):
  dicti = {	'.-'	:'A', 	'-.':'N',		'.----':'1',
	'-...':'B'	, 	'---':'O'	,'..---':'2',
	'-.-.':'C' ,	'.--.': 'P',	'...--':'3',
	'-..':'D',		'--.-':'Q'	, '....-':'4',
	'.':'E',	'.-.':'R'	,	'.....':'5',
	'..-.':'F',		'...':'S'	, 	'-....':'6',
	'--.':'G' ,	'-':'T'	,  '--...':'7',
	'....':'H' ,	'..-':'U',	'---..':'8',
	'..':'I',	'...-':'V',  '----.':'9',
	'.---':'J' ,	'.--':'W',	'-----':'0',
 '-.-':'K'	, '-..-':'X',
	'.-..':'L',	'-.--':'Y',
	'--':'M',	'--..':'Z'}
  decod=''
  for i in code.split(' '):
    if i == '/':
      decod +=' '
    else:
      decod += dicti.get(i,'')
  return decod
morse1= ".-- . .-.. -.-. --- -- . / .. -. / - .... . / -- .-.. / -.-. --- ..- .-. ... ."
d=morse(morse1)
print("A megoldás: ",d)

A megoldás:  WELCOME IN THE ML COURSE
